In [38]:
import numpy as np
import torch

### Creating and Initializing

### Dimensions

In [22]:
one_dimension = torch.empty(2)
two_dimensions = torch.empty(2, 2)
three_dimensions = torch.empty(2, 2, 2)
four_dimensions = torch.empty(2, 2, 2, 2)

print(one_dimension)
print(two_dimensions)
print(three_dimensions)
print(four_dimensions)

tensor([0., 0.])
tensor([[7.0065e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])
tensor([[[0.0000e+00, 0.0000e+00],
         [1.0802e-05, 1.6968e-07]],

        [[3.3795e+21, 6.7948e-07],
         [1.3592e+22, 2.0314e+20]]])
tensor([[[[-2.5364e+20,  4.5912e-41],
          [ 8.9683e-44,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  2.0000e+00],
          [ 1.3000e+22,  5.3927e-05]],

         [[ 6.6762e-07,  4.1956e-08],
          [ 1.0315e-08,  3.4152e-06]]]])


### A Real World ML Example

In [ ]:
batchs = 2
samples = 3
features = 15
x = torch.rand(batchs, samples, features)
x

In [ ]:
batchs = 2
samples = 3
features = 15
x = torch.zeros(batchs, samples, features)
x

In [2]:
batchs = 2
samples = 3
features = 15
x = torch.ones(batchs, samples, features)
x

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

TODO: Get a list of all available datatypes.

### Datatypes

In [4]:
batchs = 2
samples = 3
features = 15
x = torch.ones(batchs, samples, features, dtype=int)

print(x.dtype)
print(x)

torch.int64
tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]])


In [23]:
x.size()

torch.Size([2, 2])

In [13]:
x = torch.tensor([1, 1, 1])
print(x.dtype)
print(x.size())
print(x)

torch.int64
torch.Size([3])
tensor([1, 1, 1])


### Arithmatic Operations

In [9]:
y = torch.tensor([2, 2, 2])
z = x + y

print(x)
print(y)
print(z)

tensor([1, 1, 1])
tensor([2, 2, 2])
tensor([3, 3, 3])


In [14]:
z = x.add(y)

print(z)

tensor([5, 5, 5])


The underscore methods in Pytorch represent in place modifications. The method below still returns a value which is x itself however you only need to use it in this fashion if you want to modify x and set it into another variable.


In [17]:
print(x)

x.add_(y)

print(x)

b = x.add_(y)

print(b is x)

tensor([4, 4, 4])
tensor([8, 8, 8])
True


TODO: Get a list of all the basic arithmatic operations.

### Slicing

In [20]:
# Slicing - second row all columns
x = torch.rand(2,2)
print(x)
print(x[1, :])

tensor([[0.7837, 0.2942],
        [0.0705, 0.5885]])
tensor([0.0705, 0.5885])


In [21]:
# Slicing - all rows first column
x = torch.rand(2,2)
print(x)
print(x[:, 0])

tensor([[0.7873, 0.4953],
        [0.7367, 0.2333]])
tensor([0.7873, 0.7367])


In [25]:
# Using the item() method to return a scalar. Notice from the output that z is no longer a tensor.
z = x[1, 1]

print(x)
print(z.item())

tensor([[0.7873, 0.4953],
        [0.7367, 0.2333]])
0.23329925537109375


### Reshaping

You can reshape a tensor as long as you account for every element in the original tensor. The example below transforms a two dimension 2 by 5 tensor into a one dimensional tensor containing 10 elements. 

You an also have Pytorch determine a dimension for you.

Try using an incorrect values for view that do not account for every element in the original tensor and see what happens.

In [31]:
x = torch.rand(2, 5)
y = x.view(10)
z = x.view(-1,2)

print(x)
print(x.size())
print(y)
print(y.size())
print(z)
print(z.size())

tensor([[0.5232, 0.7968, 0.9853, 0.7489, 0.4842],
        [0.0138, 0.0899, 0.8297, 0.3014, 0.6698]])
torch.Size([2, 5])
tensor([0.5232, 0.7968, 0.9853, 0.7489, 0.4842, 0.0138, 0.0899, 0.8297, 0.3014,
        0.6698])
torch.Size([10])
tensor([[0.5232, 0.7968],
        [0.9853, 0.7489],
        [0.4842, 0.0138],
        [0.0899, 0.8297],
        [0.3014, 0.6698]])
torch.Size([5, 2])


### Converting between tensors and Numpy arrays.

You can convert from a tensor to a numpy array using a tensor's numpy method however the two variables share the same memory location. In other words changing one will change the other.

In [35]:
x = torch.zeros(3, 4)
z = x.numpy()

print(x)
print(z)
print(type(z))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [36]:
x[1,1] = 1

print(x)
print(z)
print(type(z))

tensor([[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.]])
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [45]:
x = np.ones((5, 5), dtype=int)
y = torch.from_numpy(x)

print(x)
print(type(x))
print(y)
print(type(y))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
<class 'numpy.ndarray'>
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
<class 'torch.Tensor'>


In [46]:
# Be careful when modifying one because you will modify the other.
x += 1

print(x)
print(y)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
tensor([[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]])
