https://www.youtube.com/watch?v=DbeIqrwb_dE<br>

requires_grad is False by default.<br>
When it is set to True PyTorch will calculate a computational graph for the tensor.

In [1]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

tensor([0.5512, 0.9186, 0.5713], requires_grad=True)


Mention forward pass, back propagation. Also mention the AddBackward0 function in the grad_fn attribute.

In [2]:
y = x+2
print(y)


tensor([2.5512, 2.9186, 2.5713], grad_fn=<AddBackward0>)


In [3]:
z = y*y*2
z

tensor([13.0169, 17.0359, 13.2228], grad_fn=<MulBackward0>)

In [4]:
a = z.mean()
a

tensor(14.4252, grad_fn=<MeanBackward0>)


To calcualte the gradients call backward() to calcualte the gradient of z with respect to x often written as dz/dx.<br>
Show the error that occurs when requires_grad is set to False and you try to do a backward pass.

In [5]:
a.backward()
print(x.grad)

tensor([3.4016, 3.8914, 3.4283])


In [6]:
v = torch.tensor([0.1, 0.2, 0.3], dtype=torch.float32)
z.backward(v)
x.grad

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [11]:
test = torch.randn(3, requires_grad=True)
print(test)

#test.requires_grad_(False) # Trailing underscore means that the variable will be modified in place.
#print(test)

#new = test.detach() # Creates a new tensor.
#print(new)

new1  = test + 2
print(test)
print(new1)

with torch.no_grad():
    new2  = test + 2
    print(test)
    print(new2)



tensor([-1.2932, -0.6325,  0.2601], requires_grad=True)
tensor([-1.2932, -0.6325,  0.2601], requires_grad=True)
tensor([0.7068, 1.3675, 2.2601], grad_fn=<AddBackward0>)
tensor([-1.2932, -0.6325,  0.2601], requires_grad=True)
tensor([0.7068, 1.3675, 2.2601])


In [14]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    #weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [15]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor