In [1]:
import torch

The torch.stack function concatenates tensors along a dimension.
According to the Pytorch online documentation the stack function "concatenates a sequence of tensors along a new dimension". This description can be a little jargon heavy if you are coming at this for the first time. Let's unpack it with a simple example.

https://pytorch.org/docs/stable/generated/torch.stack.html

In [28]:
x = [[1, 2, 3], [3, 4, 6]]
y = [[9, 8, 7], [6, 5, 16]]

x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)
z =torch.stack([x, y])

print(z)
print(z.shape)

tensor([[[ 1.,  2.,  3.],
         [ 3.,  4.,  6.]],

        [[ 9.,  8.,  7.],
         [ 6.,  5., 16.]]])
torch.Size([2, 2, 3])


In [37]:
r = torch.mean(z, 2)

r

tensor([[2.0000, 4.3333],
        [8.0000, 9.0000]])

In [56]:
z[:,0,0]

tensor([1., 9.])