### Contents
Introduction<br>
Creating Tensors<br>
Initializing Tensors<br>
Dimensions and Shapes<br>
Data types<br>
Converting Between Tensors and Numpy Arrays<br>
Basic Arithmatic operations<br>
Slicing<br>
Reshaping<br>
Next Steps<br>
Conclusion<br>

In [ ]:
import numpy as np
import torch

In [21]:
data_as_list = [1, 2, 3]

data_as_tensor = torch.tensor(data_as_list)

print(data_as_list)
print(data_as_tensor)

[1, 2, 3]
tensor([1, 2, 3])


In [20]:
data_as_numpy_array = np.array([1, 2, 3])

data_as_tensor = torch.tensor(data_as_list)

print(data_as_numpy_array)
print(data_as_tensor)

[1 2 3]
tensor([1, 2, 3])


### Dimensions

In [ ]:
one_dimension = torch.empty(2)
four_dimensions = torch.empty(2, 2, 2, 2)

print(one_dimension)
print(four_dimensions)

In [18]:
two_dimensional_tensor = torch.zeros((2, 2), dtype=torch.int64)

print(two_dimensional_tensor)
print(two_dimensional_tensor.ndim)

tensor([[0, 0],
        [0, 0]])
2


In [15]:
three_dimensional_tensor = torch.ones((2, 2, 2), dtype=torch.float64)

print(three_dimensional_tensor)
print(three_dimensional_tensor.ndim)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]], dtype=torch.float64)
3


### A Real World ML Example

In [ ]:
batchs = 2
samples = 3
features = 15
x = torch.rand(batchs, samples, features)
x

In [ ]:
batchs = 2
samples = 3
features = 15
x = torch.zeros(batchs, samples, features)
x

In [ ]:
batchs = 2
samples = 3
features = 15
x = torch.ones(batchs, samples, features)
x

TODO: Get a list of all available datatypes.

### Datatypes

In [ ]:
batchs = 2
samples = 3
features = 15
x = torch.ones(batchs, samples, features, dtype=int)

print(x.dtype)
print(x)

In [ ]:
x.size()

In [ ]:
x = torch.tensor([1, 1, 1])
print(x.dtype)
print(x.size())
print(x)

### Arithmatic Operations

In [ ]:
y = torch.tensor([2, 2, 2])
z = x + y

print(x)
print(y)
print(z)

In [ ]:
z = x.add(y)

print(z)

The underscore methods in Pytorch represent in place modifications. The method below still returns a value which is x itself however you only need to use it in this fashion if you want to modify x and set it into another variable.


In [ ]:
print(x)

x.add_(y)

print(x)

b = x.add_(y)

print(b is x)

TODO: Get a list of all the basic arithmatic operations.

### Slicing

In [ ]:
# Slicing - second row all columns
x = torch.rand(2,2)
print(x)
print(x[1, :])

In [ ]:
# Slicing - all rows first column
x = torch.rand(2,2)
print(x)
print(x[:, 0])

In [ ]:
# Using the item() method to return a scalar. Notice from the output that z is no longer a tensor.
z = x[1, 1]

print(x)
print(z.item())

### Reshaping

You can reshape a tensor as long as you account for every element in the original tensor. The example below transforms a two dimension 2 by 5 tensor into a one dimensional tensor containing 10 elements. 

You an also have Pytorch determine a dimension for you.

Try using an incorrect values for view that do not account for every element in the original tensor and see what happens.

In [ ]:
x = torch.rand(2, 5)
y = x.view(10)
z = x.view(-1,2)

print(x)
print(x.size())
print(y)
print(y.size())
print(z)
print(z.size())

### Converting between tensors and Numpy arrays.

You can convert from a tensor to a numpy array using a tensor's numpy method however the two variables share the same memory location. In other words changing one will change the other.

In [ ]:
x = torch.zeros(3, 4)
z = x.numpy()

print(x)
print(z)
print(type(z))

In [ ]:
x[1,1] = 1

print(x)
print(z)
print(type(z))

In [ ]:
x = np.ones((5, 5), dtype=int)
y = torch.from_numpy(x)

print(x)
print(type(x))
print(y)
print(type(y))

In [ ]:
# Be careful when modifying one because you will modify the other.
x += 1

print(x)
print(y)