### Contents
A Simple Shape Change<br>
Shared Memory<br>
A Simple Shape Change<br>
Allowable Views<br>
Changing Rank (or number of dimensions)<br>
Shorthand Notation for Creating Vectors<br>

In [15]:
import torch

### A Simple Shape Change

In [34]:
data = [[1,2],[3,4],[5,6]]
base_tensor = torch.tensor(data)

print(base_tensor)
print('ndim', base_tensor.ndim)
print('Shape', base_tensor.shape)
view_tensor = base_tensor.view(2, 3)

print('\n', view_tensor)
print('ndim', view_tensor.ndim)
print('Shape', view_tensor.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
ndim 2
Shape torch.Size([3, 2])

 tensor([[1, 2, 3],
        [4, 5, 6]])
ndim 2
Shape torch.Size([2, 3])


### Shared Memory

In [18]:
base_tensor[0][0] = 9

print(view_tensor)

tensor([[9, 2, 3],
        [4, 5, 6]])


### Allowable Shapes

In [19]:
bad_view = base_tensor.view(3, 3)

print(bad_view)

RuntimeError: shape '[3, 3]' is invalid for input of size 6

### Another Example

In [22]:
data = [[1,2,3,3],[5,6,7,8],[9,10,11,12]]
data_tensor = torch.tensor(data)

print(data_tensor)
print('ndim', data_tensor.ndim)
print('Shape', data_tensor.shape)

view_of_tensor = data_tensor.view(2, 6)
print('\n', view_of_tensor)
print('ndim', view_of_tensor.ndim)
print('Shape', view_of_tensor.shape)


tensor([[ 1,  2,  3,  3],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
ndim 2
Shape torch.Size([3, 4])

 tensor([[ 1,  2,  3,  3,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
ndim 2
Shape torch.Size([2, 6])


### Changing Rank (or number of dimensions)

In [28]:
cube_tensor = torch.ones(2, 3, 4)

print(cube_tensor)
print('ndim', cube_tensor.ndim)
print('Shape', cube_tensor.shape)

view_of_tensor = cube_tensor.view(2, 2, 2, 3)
print('\n', view_of_tensor)
print('ndim', view_of_tensor.ndim)
print('Shape', view_of_tensor.shape)



tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
ndim 3
Shape torch.Size([2, 3, 4])

 tensor([[[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]]])
ndim 4
Shape torch.Size([2, 2, 2, 3])


### Shorthand Notation for Creating Vectors

In [32]:
cube_tensor = torch.ones(2, 3, 4)

print(cube_tensor)
print('ndim', cube_tensor.ndim)
print('Shape', cube_tensor.shape)

vector_view = cube_tensor.view(-1)
print('\n', vector_view)
print('ndim', vector_view.ndim)
print('Shape', vector_view.shape)


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
ndim 3
Shape torch.Size([2, 3, 4])

 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.])
ndim 1
Shape torch.Size([24])


### Another vector example

In [33]:
cube_tensor = torch.ones(2, 3, 4)

print(cube_tensor)
print('ndim', cube_tensor.ndim)
print('Shape', cube_tensor.shape)

vector_view = cube_tensor.view(2, -1)
print('\n', vector_view)
print('ndim', vector_view.ndim)
print('Shape', vector_view.shape)


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
ndim 3
Shape torch.Size([2, 3, 4])

 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
ndim 2
Shape torch.Size([2, 12])
