requires_grad is False by default.<br>
When it is set to True PyTorch will calculate a computational graph for the tensor.

In [1]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

tensor([-1.6196,  0.6660, -2.7358], requires_grad=True)


Mention forward pass, back propagation. Also mention the AddBackward0 function in the grad_fn attribute.

In [2]:
y = x+2
print(y)


tensor([ 0.3804,  2.6660, -0.7358], grad_fn=<AddBackward0>)


In [3]:
z = y*y*2
z

tensor([ 0.2895, 14.2149,  1.0827], grad_fn=<MulBackward0>)

In [4]:
z = z.mean()
z

tensor(5.1957, grad_fn=<MeanBackward0>)


To calcualte the gradients call backward() to calcualte the gradient of z with respect to x often written as dz/dx.<br>
Show the error that occurs when requires_grad is set to False and you try to do a backward pass.

In [5]:
z.backward()
print(x.grad)

tensor([ 0.5072,  3.5546, -0.9810])
