### Contents
Creating and Initializing<br>
Dimensions<br>
Data types<br>
Converting Between Tensors and Numpy Arrays<br>
Basic Arithmatic operations<br>
Slicing<br>
Reshaping<br>
Next Steps<br>
Conclusion<br>

In [2]:
import numpy as np
import torch

### Dimensions

In [ ]:
one_dimension = torch.empty(2)
two_dimensions = torch.empty(2, 2)
three_dimensions = torch.empty(2, 2, 2)
four_dimensions = torch.empty(2, 2, 2, 2)

print(one_dimension)
print(two_dimensions)
print(three_dimensions)
print(four_dimensions)

In [13]:
y = np.array([[1, 2, 3],[4, 5, 6]])
x = torch.Tensor(y)
y[0][0] = 7
print(x.ndim)
print(x.shape)
print(x)
print(y)

2
torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
[[7 2 3]
 [4 5 6]]


### A Real World ML Example

In [ ]:
batchs = 2
samples = 3
features = 15
x = torch.rand(batchs, samples, features)
x

In [ ]:
batchs = 2
samples = 3
features = 15
x = torch.zeros(batchs, samples, features)
x

In [ ]:
batchs = 2
samples = 3
features = 15
x = torch.ones(batchs, samples, features)
x

TODO: Get a list of all available datatypes.

### Datatypes

In [ ]:
batchs = 2
samples = 3
features = 15
x = torch.ones(batchs, samples, features, dtype=int)

print(x.dtype)
print(x)

In [ ]:
x.size()

In [ ]:
x = torch.tensor([1, 1, 1])
print(x.dtype)
print(x.size())
print(x)

### Arithmatic Operations

In [ ]:
y = torch.tensor([2, 2, 2])
z = x + y

print(x)
print(y)
print(z)

In [ ]:
z = x.add(y)

print(z)

The underscore methods in Pytorch represent in place modifications. The method below still returns a value which is x itself however you only need to use it in this fashion if you want to modify x and set it into another variable.


In [ ]:
print(x)

x.add_(y)

print(x)

b = x.add_(y)

print(b is x)

TODO: Get a list of all the basic arithmatic operations.

### Slicing

In [ ]:
# Slicing - second row all columns
x = torch.rand(2,2)
print(x)
print(x[1, :])

In [ ]:
# Slicing - all rows first column
x = torch.rand(2,2)
print(x)
print(x[:, 0])

In [ ]:
# Using the item() method to return a scalar. Notice from the output that z is no longer a tensor.
z = x[1, 1]

print(x)
print(z.item())

### Reshaping

You can reshape a tensor as long as you account for every element in the original tensor. The example below transforms a two dimension 2 by 5 tensor into a one dimensional tensor containing 10 elements. 

You an also have Pytorch determine a dimension for you.

Try using an incorrect values for view that do not account for every element in the original tensor and see what happens.

In [ ]:
x = torch.rand(2, 5)
y = x.view(10)
z = x.view(-1,2)

print(x)
print(x.size())
print(y)
print(y.size())
print(z)
print(z.size())

### Converting between tensors and Numpy arrays.

You can convert from a tensor to a numpy array using a tensor's numpy method however the two variables share the same memory location. In other words changing one will change the other.

In [ ]:
x = torch.zeros(3, 4)
z = x.numpy()

print(x)
print(z)
print(type(z))

In [ ]:
x[1,1] = 1

print(x)
print(z)
print(type(z))

In [ ]:
x = np.ones((5, 5), dtype=int)
y = torch.from_numpy(x)

print(x)
print(type(x))
print(y)
print(type(y))

In [ ]:
# Be careful when modifying one because you will modify the other.
x += 1

print(x)
print(y)